version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: multipart
    versions:
    - "> 0.1"
  - dependency-name: redis
    versions:
    - "< 2.10.7, >= 2.10.6.a"
  - dependency-name: yapf
    versions:
    - ">= 0.26.a, < 0.27"
  - dependency-name: responses
    versions:
    - 0.13.1
  - dependency-name: tox
    versions:
    - '>= 3.24.4'
  - dependency-name: cryptography
    versions:
    - 3.4.1
  - dependency-name: coverage
    versions:
    - ">= 7.2.1"
